/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-variant": "#2d3449",
        "surface-container-highest": "#2d3449",
        "on-error": "#690005",
        surface: "#0b1326",
        primary: "#c0c1ff",
        "on-primary-fixed": "#07006c",
        "secondary-fixed": "#dde1ff",
        "primary-fixed": "#e1e0ff",
        "on-surface-variant": "#c7c4d7",
        tertiary: "#4cd7f6",
        "inverse-on-surface": "#283044",
        "surface-bright": "#31394d",
        "on-tertiary-fixed": "#001f26",
        "on-error-container": "#ffdad6",
        "surface-tint": "#c0c1ff",
        "secondary-fixed-dim": "#b8c4ff",
        "on-surface": "#dae2fd",
        "inverse-primary": "#494bd6",
        "surface-container-lowest": "#060e20",
        "tertiary-container": "#009eb9",
        "surface-container-high": "#222a3d",
        "on-secondary-container": "#a2b1f9",
        "on-primary": "#1000a9",
        "primary-container": "#8083ff",
        "outline-variant": "#464554",
        "surface-container": "#171f33",
        "surface-dim": "#0b1326",
        "surface-container-low": "#131b2e",
        outline: "#908fa0",
        "secondary-container": "#334282",
        "on-tertiary": "#003640",
        "primary-fixed-dim": "#c0c1ff",
        "error-container": "#93000a",
        "tertiary-fixed": "#acedff",
        "on-tertiary-container": "#002f38",
        "on-primary-container": "#0d0096",
        "on-secondary": "#1a2b6a",
        "on-secondary-fixed": "#001354",
        "inverse-surface": "#dae2fd",
        "on-tertiary-fixed-variant": "#004e5c",
        secondary: "#b8c4ff",
        "on-primary-fixed-variant": "#2f2ebe",
        background: "#0b1326",
        "tertiary-fixed-dim": "#4cd7f6",
        "on-background": "#dae2fd",
        error: "#ffb4ab",
        "on-secondary-fixed-variant": "#334282",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1280px",
        "section-gap": "96px",
        unit: "8px",
        "margin-mobile": "20px",
        "stack-lg": "40px",
        "stack-sm": "12px",
        gutter: "24px",
        "stack-md": "20px",
        "margin-desktop": "48px",
      },
      fontFamily: {
        "headline-lg": ["Inter"],
        "headline-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "mono-sm": ["Geist"],
        "display-xl": ["Inter"],
        "label-md": ["Geist"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
      },
      fontSize: {
        "headline-lg": [
          "40px",
          { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-lg-mobile": [
          "32px",
          { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "mono-sm": ["13px", { lineHeight: "1.5", fontWeight: "400" }],
        "display-xl": [
          "64px",
          { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" },
        ],
        "label-md": [
          "14px",
          { lineHeight: "1.4", letterSpacing: "0.02em", fontWeight: "500" },
        ],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
