import { Subject } from "@/types/subject";

export const subjects: Subject[] = [
  {
    id: 1,
    title: "Physics",
    description: "Mechanics, Electricity, Modern Physics",
    chapters: 12,
    level: "Advanced",
    badge: "POPULAR",
    icon: "flare",
  },
  {
    id: 2,
    title: "Chemistry",
    description: "Organic, Inorganic, Physical",
    chapters: 15,
    level: "Advanced",
    badge: "TRENDING",
    icon: " menu_book",
  },
  {
    id: 3,
    title: "Biology",
    description: "Botany, Zoology, Genetics",
    chapters: 18,
    level: "Intermediate",
    icon: "vital_signs",
  },
  {
    id: 4,
    title: "Mathematics",
    description: "Algebra, Geometry, Calculus",
    chapters: 24,
    level: "Expert",
    badge: "TOP PICK",
    icon: "architecture",
  },
  // {
  //   id: 5,
  //   title: "Social Science",
  //   description: "History, Civics, Geography",
  //   chapters: 16,
  //   level: "Standard",
  //   icon: <Globe size={28} />,
  // },
  // {
  //   id: 6,
  //   title: "English",
  //   description: "Grammar, Literature, Writing",
  //   chapters: 14,
  //   level: "Standard",
  //   icon: <BookOpen size={28} />,
  // },
  // {
  //   id: 7,
  //   title: "Hindi",
  //   description: "Grammar, Poetry, Literature",
  //   chapters: 13,
  //   level: "Standard",
  //   icon: <Languages size={28} />,
  // },
  // {
  //   id: 8,
  //   title: "Computer Science",
  //   description: "Programming, AI, Data",
  //   chapters: 10,
  //   level: "Advanced",
  //   badge: "AI READY",
  //   icon: <Monitor size={28} />,
  // },
];
