import type { Metadata } from "next";
import "./globals.css";

import { Inter, Plus_Jakarta_Sans } from "next/font/google";
import GridHome from "@/components/common/GridHome";

export const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const jakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-jakarta",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${jakarta.variable} h-full antialiased`}>
      <body className="overflow-x-hidden selection:bg-primary/30">
        <GridHome />
        {children}
      </body>
    </html>
  );
}
